<a href="https://colab.research.google.com/github/PedroAlmeida18/PGP3_TESTESIND/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
# CURSO DE APRENDIZADO COM DEPP LEARNING
# Aprendendo a transformar em tensores
lista = [[1,2,3],[4,5,6]]
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)


tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)


tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)


tns = torch.LongTensor(lista) #Uso para inteiros
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
||||||||||||||||||
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
||||||||||||||||||
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
||||||||||||||||||
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
#Outras formas de instaciar tensores, PRESERVA O TIPO DO ARRAY PÁRA O TENSOR
import numpy as np
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print("CRIAÇÃO DO ARRAY")
print(arr)
print("CONVERSÃO EM TENSORES ")
print(tns)

CRIAÇÃO DO ARRAY
[[0.12479968 0.72920524 0.45762437 0.31132518]
 [0.79053827 0.40033574 0.76430888 0.19401772]
 [0.36130525 0.79807388 0.62815591 0.40150112]]
CONVERSÃO EM TENSORES 
tensor([[0.1248, 0.7292, 0.4576, 0.3113],
        [0.7905, 0.4003, 0.7643, 0.1940],
        [0.3613, 0.7981, 0.6282, 0.4015]], dtype=torch.float64)


# Tensores já inicializados

In [8]:
tns1 = torch.ones(2,3)
tns0= torch.zeros(4,5)
tnsr= torch.randn(3,3)
print(tns1)
print(tns0 )
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.7702,  1.0433,  0.7959],
        [-1.0500, -0.9926,  0.1611],
        [-2.6683, -1.1602, -0.7309]])


#Voltar o tensor em um array

In [9]:
tnsr=tnsr.data.numpy()
print(arr)

[[0.12479968 0.72920524 0.45762437 0.31132518]
 [0.79053827 0.40033574 0.76430888 0.19401772]
 [0.36130525 0.79807388 0.62815591 0.40150112]]


In [13]:
print(tnsr)
tnsr[0,2]=-10
print(tnsr)
print('')
print("Acesso de algumas linhas de um, tensor")
print (tnsr[0:2])

[[  0.7702491    1.0432711  -10.        ]
 [ -1.0500077   -0.99261916   0.16105306]
 [ -2.6682904   -1.1602085   -0.73093057]]
[[  0.7702491    1.0432711  -10.        ]
 [ -1.0500077   -0.99261916   0.16105306]
 [ -2.6682904   -1.1602085   -0.73093057]]

Acesso de algumas linhas de um, tensor
[[  0.7702491    1.0432711  -10.        ]
 [ -1.0500077   -0.99261916   0.16105306]]


#Operações com Tensores

In [18]:
#Obs: CADA ELEMENTO DE UM TENSOR, OPERA COM RESPECTIVO ELEMENTO DO OUTRO TENSOR
tnsmod= tnsr[0:2,:]
print(tnsmod)
print(tns1)
print(tns1-tnsmod)


[[  0.7702491    1.0432711  -10.        ]
 [ -1.0500077   -0.99261916   0.16105306]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.2298, -0.0433, 11.0000],
        [ 2.0500,  1.9926,  0.8389]])


#TESTE PARA GPU

In [2]:
import torch
tnstestegpu=torch.randn(10)
if torch.cuda.is_available():
  device=torch.device('cuda')
else :
  device = torch.device('cpu')
print(device)

tnstestegpu=tnstestegpu.to(device)
print(tnstestegpu)

cuda
tensor([-0.0069, -1.2262,  0.2741,  0.4084, -1.3687,  0.2833,  1.5371, -0.8482,
        -0.0912, -1.3501], device='cuda:0')
